<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>firstLineMatch</key>
	<string>==</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Rdoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(?=\S)(?![=-]{3,}(?=$))</string>
			<key>end</key>
			<string>^(?:\s*$|(?=[ ]{,3}&gt;.))|(?=[ \t]*\n)(?&lt;=^===|^====|=====|^---|^----|-----)[ \t]*\n</string>
			<key>name</key>
			<string>markup.heading.rdoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(={3,})(?=[ \t]*$)</string>
					<key>name</key>
					<string>markup.heading.1.markdown</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(-{3,})(?=[ \t]*$)</string>
					<key>name</key>
					<string>markup.heading.2.markdown</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.rdoc</string>
	<key>uuid</key>
	<string>4923E00C-3A77-452C-8AD7-7B2E2989029F</string>
</dict>
</plist>
