#!/usr/bin/env ruby
APP_ROOT = File.join(File.dirname(__FILE__), '..')

begin
  require 'rubigen'
rescue LoadError
  require 'rubygems' unless ENV['NO_RUBYGEMS']
  require 'rubigen'
end
require 'rubigen/scripts/destroy'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! :rubygems, :newgem
RubiGen::Scripts::Destroy.new.run(ARGV)
